### PR TITLE
VFB-313: migration to fix problematic old seed data

### PR DESCRIPTION
**Pull request by stonelink**
## What's changed
Replace 3 Cambridge postcodes on `dev` and `staging`.
The seed data was already fixed to have all London postcodes, so this is only for test databases that we don't want to wipe - notably `staging` has a lot of test data that the users have added.

I'm not convinced that this should be a migration, but since there's only test data atm it won't cause a problem. 
I'd be happy to just run these queries in the supabase console if we agree that that's better.

## Checklist
- [X] The ticket is up-to-date - Please document any deviations from the original approach if there is any.
- [X] I have documented the testing steps for QA
- [X] I have self-reviewed this PR
- [X] Make sure you've verified it works via `npm run dev`
- [X] Make sure you've verified it works via `npm run build` and `npm run start`
- [X] Make sure you've fixed all linting problems with `npm run lint_fix`
- [X] Make sure you've tested via `npm run test`

If you have made any changes to the database...
  - [ ] The migration files are up-to-date with my final set up (`npx supabase db diff -f <name_of_migration>` should create nothing at this point)
  - [-] I have updated the typescript definitions for the database with `npm run generate_types:local`
  - [-] I have modified the seed in `supabase/seed/seed.mts` if appropriate
  - [-] If I have modified the seed, I have also generated the seed with `npm run db:generate_seed` 
  - [ ] With my final set up, I can run `npm run reset_supabase` without any errors.
  - [ ] (Just before merging the ticket) I have updated the timestamps of the new migration files so that they are after all existing migration files.
  - [X] I have taken reasonable measures to ensure constraint violations do not happen when the migration occurs, e.g.:
    - audit_log FK constraints that could be violated
    - any constraints that I have added, e.g. `set not null`
  - [ ] I have checked that migration can happen successfully without resetting the database, doing the following.
    - Make sure you have rebased your branch onto dev or merged dev into your branch.
    - Checkout the dev branch
    - Run `npm run post_checkout` to reset the database, including the seed data.
    - Checkout your branch
    - Run `npx supabase migrations up --include-all --local` to run all outstanding migration files
    - Check that the resulting database is what you expect, bar any seed data changes.

---
## AI generated change summary

The following is a summary of the changes in the PR generated by [What The Diff](https://whatthediff.ai/).
Delete the command below if you don't want this to be generataed.

wtd:summary

### CODE REVIEW

**Comment by stonelink** [comment]
I've thought a bit more about this and rather than having a migration I suggest using the Supabase SQL Editor interface for the environment to run the three update queries separately, with a rollback check:

```
START TRANSACTION;
UPDATE public.clients SET address_postcode = 'SE11 5RD' WHERE address_postcode = 'CB2 3JU' RETURNING *;
ROLLBACK;
```

then checking that the number of rows in the output (that would be changed) is reasonable, then changing the ROLLBACK to COMMIT and running the command again.

And similarly for the other two.

What do you think?

**Review by Stuart-Knowles-SW — COMMENTED** [review]
~If this is just to replace historic data we can run it directly in supabase rather than commit it as a migration?~

Edit: just saw you'd had the same thought

**Comment by Stuart-Knowles-SW** [comment]
> I've thought a bit more about this and rather than having a migration I suggest using the Supabase SQL Editor interface for the environment to run the three update queries separately, with a rollback check:
> 
> ```
> START TRANSACTION;
> UPDATE public.clients SET address_postcode = 'SE11 5RD' WHERE address_postcode = 'CB2 3JU' RETURNING *;
> ROLLBACK;
> ```
> 
> then checking that the number of rows in the output (that would be changed) is reasonable, then changing the ROLLBACK to COMMIT and running the command again.
> 
> And similarly for the other two.
> 
> What do you think?

Honestly I think this is a very low risk change. The rollback check is sensible, but I don't think we need to be worried about this.

**Comment by stonelink** [comment]
Thanks for your thoughts on this. Please excuse my excess of caution.

I'll abandon this PR.

**Pull request closed without merging**
